version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - tech_debt_ai_default

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  tech_debt_ai_default:
    external: true 